version: "3.9"
services:
  in-store:
    build: .
    ports:
      - "8080:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/swagger.yaml