/*
 * Swagger inStore
 *
 * API version: 1.0.0
 * Contact: eyuparslana@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"fmt"
	"net/http"

	"inStore/config"
	"inStore/handler"
	"inStore/logger"
	"inStore/task"
)

func main() {
	task.StartTask()
	task.CheckExistingData()
	mux := http.NewServeMux()
	mux.HandleFunc("/", handler.Home)
	mux.HandleFunc("/set", handler.Set)
	mux.HandleFunc("/get", handler.Get)
	mux.HandleFunc("/flush", handler.Flush)
	logger.Info.Println("Server starting...")
	logger.Info.Printf("Server started at %s", config.API_PORT)
	logger.Fatal.Println(http.ListenAndServe(fmt.Sprintf(":%s", config.API_PORT), mux))
}
