name: Lint Go Code
on: [ push ]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go fmt ./...