push:
  branches:
    - master

name: Test

jobs:
  test:
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Checkout code
        uses: actions/checkout@master
      - name: Test
        run: go test ./handler